Prevent crash
The Plugin Kern-A-Lytics.glyphsFilter has caused a crash in Glyphs 2.5.2-1167.

Details:

```
Traceback (most recent call last):

 File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaList.py", line 53, in observeValueForKeyPath_ofObject_change_context_
   self._targetMethod()

 File "~/Library/Application Support/Glyphs/Scripts/vanilla/vanillaList.py", line 791, in _selection
   self._selectionCallback(self)

 File "~/Library/Application Support/Glyphs/Repositories/Kern-A-Lytics/Kern-A-Lytics.glyphsFilter/Contents/Resources/kernGraph.py", line 458, in list_callback
   repr_glyphs = [f[g_name] for g_name in repr_pair]

TypeError: 'NoneType' object is not iterable
```